# Generated by Django 4.1.1 on 2022-09-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('cod_arbitro', models.IntegerField(db_column='Cod_Arbitro', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('idade', models.CharField(db_column='Idade', max_length=45)),
                ('sexo', models.CharField(db_column='Sexo', max_length=45)),
                ('pais', models.CharField(db_column='Pais', max_length=45)),
                ('confederacao', models.CharField(db_column='Confederacao', max_length=45)),
            ],
            options={
                'db_table': 'arbitro',
                'managed': True,
            },
        ),
    ]
