# Generated by Django 4.1.1 on 2022-09-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copa', '0002_arbitro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('cod_estadio', models.IntegerField(db_column='Cod_Estadio', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('capacidade', models.CharField(db_column='Capacidade', max_length=45)),
                ('cidade', models.CharField(db_column='Cidade', max_length=45)),
                ('ano', models.CharField(db_column='Ano', max_length=45)),
            ],
            options={
                'db_table': 'estadio',
                'managed': True,
            },
        ),
    ]
