# Generated by Django 4.1.1 on 2022-09-13 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copa', '0003_estadio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('cod_estatistica', models.IntegerField(db_column='Cod_Estatistica', primary_key=True, serialize=False)),
                ('golo', models.CharField(blank=True, db_column='Golo', max_length=45, null=True)),
                ('falta', models.CharField(blank=True, db_column='Falta', max_length=45, null=True)),
                ('amarelo', models.CharField(blank=True, db_column='Amarelo', max_length=45, null=True)),
                ('vermelho', models.CharField(blank=True, db_column='Vermelho', max_length=45, null=True)),
                ('lesao', models.CharField(blank=True, db_column='Lesao', max_length=45, null=True)),
            ],
            options={
                'db_table': 'estatistica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('cod_grupo', models.IntegerField(db_column='Cod_Grupo', primary_key=True, serialize=False)),
                ('jogo', models.IntegerField(db_column='Jogo')),
                ('vitoria', models.IntegerField(db_column='Vitoria')),
                ('empate', models.IntegerField(db_column='Empate')),
                ('derrota', models.IntegerField(db_column='Derrota')),
                ('gm', models.IntegerField(db_column='GM')),
                ('gs', models.IntegerField(db_column='GS')),
                ('sigla', models.CharField(blank=True, db_column='Sigla', max_length=45, null=True)),
            ],
            options={
                'db_table': 'grupo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MelhorJogador',
            fields=[
                ('cod_melhor_jogador', models.IntegerField(db_column='Cod_Melhor_Jogador', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('posicao', models.CharField(db_column='Posicao', max_length=45)),
                ('estatistica_cod_estatistica', models.ForeignKey(db_column='ESTATISTICA_Cod_Estatistica', on_delete=django.db.models.deletion.DO_NOTHING, to='copa.estatistica')),
            ],
            options={
                'db_table': 'melhor_jogador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marcador',
            fields=[
                ('cod_marcador', models.IntegerField(db_column='Cod_Marcador', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('posicao', models.CharField(db_column='Posicao', max_length=45)),
                ('estatistica_cod_estatistica', models.ForeignKey(db_column='ESTATISTICA_Cod_Estatistica', on_delete=django.db.models.deletion.DO_NOTHING, to='copa.estatistica')),
            ],
            options={
                'db_table': 'marcador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('cod_treinador', models.IntegerField(db_column='Cod_Treinador', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('idade', models.IntegerField(db_column='Idade')),
                ('sexo', models.CharField(db_column='Sexo', max_length=45)),
                ('pais', models.CharField(db_column='Pais', max_length=45)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=45, null=True)),
                ('selecao_cod_selecao', models.ForeignKey(db_column='SELECAO_Cod_Selecao', on_delete=django.db.models.deletion.DO_NOTHING, to='copa.selecao')),
            ],
            options={
                'db_table': 'treinador',
                'managed': True,
                'unique_together': {('cod_treinador', 'selecao_cod_selecao')},
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('cod_jogador', models.IntegerField(db_column='Cod_Jogador', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=45)),
                ('idade', models.IntegerField(db_column='Idade')),
                ('clubo', models.CharField(blank=True, db_column='Clubo', max_length=45, null=True)),
                ('posicao', models.CharField(db_column='Posição', max_length=45)),
                ('titulo', models.IntegerField(db_column='Titulo')),
                ('estatistica_cod_estatistica', models.ForeignKey(db_column='ESTATISTICA_Cod_Estatistica', on_delete=django.db.models.deletion.DO_NOTHING, to='copa.estatistica')),
                ('selecao_cod_selecao', models.ForeignKey(db_column='SELECAO_Cod_Selecao', on_delete=django.db.models.deletion.DO_NOTHING, to='copa.selecao')),
            ],
            options={
                'db_table': 'jogador',
                'managed': True,
                'unique_together': {('cod_jogador', 'selecao_cod_selecao')},
            },
        ),
    ]
