# Generated by Django 4.1.1 on 2022-09-13 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copa', '0004_estatistica_grupo_melhorjogador_marcador_treinador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('cod_partida', models.IntegerField(db_column='Cod_Partida', primary_key=True, serialize=False)),
                ('inicio', models.TimeField(blank=True, db_column='Inicio', null=True)),
                ('final', models.TimeField(blank=True, db_column='Final', null=True)),
                ('data', models.DateField(blank=True, db_column='Data', null=True)),
                ('golo_casa', models.IntegerField(blank=True, db_column='Golo_Casa', null=True)),
                ('marcodor', models.CharField(blank=True, db_column='Marcodor', max_length=45, null=True)),
                ('golo_visitante', models.IntegerField(blank=True, db_column='Golo_Visitante', null=True)),
                ('estadio_cod_estadio', models.ForeignKey(db_column='ESTADIO_Cod_Estadio', on_delete=django.db.models.deletion.CASCADE, to='copa.estadio')),
                ('selecao_cod_selecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_casa', to='copa.selecao')),
                ('selecao_cod_selecao1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_fora', to='copa.selecao')),
            ],
            options={
                'db_table': 'partida',
                'managed': True,
                'unique_together': {('cod_partida', 'selecao_cod_selecao', 'selecao_cod_selecao1', 'estadio_cod_estadio')},
            },
        ),
    ]
