# Generated by Django 4.1.1 on 2022-09-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copa', '0005_partida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecao',
            name='cod_selecao',
            field=models.AutoField(db_column='Cod_Selecao', primary_key=True, serialize=False),
        ),
    ]
